#!/bin/bash

function extractvendor {
    grep "^Subject:" emaildata | sed 's/\(Subject: #Accounts \)\(.*\)/\2/'
}
function extractamount {
    grep "^A:" emaildata | sed 's/\(A: \)\(.*\)/\$\2/'
}
function extractfrom {
    grep "^F:" emaildata | sed 's/\(F: \)\(.*\)/\2/'
}
function extractto {
    grep "^T:" emaildata | sed 's/\(T: \)\(.*\)/\2/'
}
vendorname=$(extractvendor)
transamount=$(extractamount)
accountfrom=$(extractfrom)
accountto=$(extractto)

echo "$(date +%Y/%m/%d) $vendorname
$accountfrom      $transamount
$accountto" >> transactioninbox.ledger


